version: "3.8"

services:
  app:
    container_name: my-net-worth
    image: my-net-worth-image
    command: uvicorn app.main:app --reload --host  0.0.0.0 --port  5000
    build:      
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    networks:
      - net-worth-net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "4"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  mongodb:
    container_name: mongodb
    image: mongo:4.2.3-bionic
    volumes:
      - mongo-data:/data/db
    networks:
      - net-worth-net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "4"
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl/certs:/etc/nginx/ssl/certs:ro
      - ./nginx/ssl/private:/etc/nginx/ssl/private:ro
    depends_on:
      - app
    networks:
      - net-worth-net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "4"

volumes:
  mongo-data:

networks:
  net-worth-net:
